name: Deploy test backend to EC2

on:
  push:
    branches: [ "test/Github-Action" ]   # 테스트 브랜치에서만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload project to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "${{ secrets.APP_DIR }}"
          rm: true

      - name: Remote deploy steps
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd "${{ secrets.APP_DIR }}"

            # .env 파일 생성
            cat > .env << 'EOF'
            NODE_ENV=production
            PORT=3000
            EOF

            # 패키지 설치
            npm install --omit=dev

            # pm2 실행/재시작
            if pm2 describe backend > /dev/null; then
              pm2 reload backend --update-env
            else
              pm2 start npm --name "backend" -- start
            fi

            pm2 save
